version: "3"
services:
  db:
    build: 
      context: ./db
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_USER: mtx
      MYSQL_PASSWORD: mtx123
      MYSQL_ROOT_PASSWORD: mtxroot
      MYSQL_DATABASE: matrix
    restart: on-failure

  frontend:
    build:
      context: ./frontend
    volumes:
      - ../apps/frontend/:/opt/matrix/
      - ../libs/node_modules:/opt/matrix/node_modules/
    ports:
      - 8089:8089
      - 8090:8090
    environment:
      DOCKER_ENV: "true"
    restart: on-failure
  backend:
    build:
      context: ./backend
    volumes:
      - ../apps/backend/:/opt/matrix/
      - ../libs/maven/:/root/.m2
    ports:
      - 8080:8080
    links:
      - db:db

volumes:

  db:
    driver: local
